import { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { AlertTriangle, ArrowLeft, Camera, CheckCircle2, Download, ExternalLink, FileCheck2, FileText, Pencil, Printer, QrCode, RotateCcw, Send, ShieldCheck, Upload, XCircle } from 'lucide-react';
import { api, downloadFile } from '../lib/api.js';
import { ErrorNotice, Loading, StatusBadge, TestResultIcon } from '../components/UI.jsx';
import { useAuth } from '../lib/auth.jsx';

export default function TestDetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const fileRef = useRef(null);
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [reviewNote, setReviewNote] = useState(''); const [evidenceSection, setEvidenceSection] = useState('construction'); const [evidenceNote, setEvidenceNote] = useState('Dossier or laboratory evidence');
  const load = () => api(`/api/tests/${id}`).then(setData).catch((reason) => setError(reason.message)); useEffect(load, [id]);
  async function uploadEvidence(event) { const file = event.target.files?.[0]; if (!file) return; const body = new FormData(); body.append('evidence', file); body.append('sectionId', evidenceSection); body.append('note', evidenceNote); setBusy(true); setError(''); try { await api(`/api/tests/${id}/evidence`, { method: 'POST', body }); await load(); } catch (reason) { setError(reason.message); } finally { setBusy(false); event.target.value = ''; } }
  async function action(path, options = {}) { setBusy(true); setError(''); try { const result = await api(`/api/tests/${id}/${path}`, { method: 'POST', ...options }); if (result.test?.id && result.test.id !== id) navigate(`/tests/${result.test.id}/edit`, { state: { justCreated: true } }); else await load(); } catch (reason) { setError(reason.message); } finally { setBusy(false); } }
  async function review(decision) { await action('review', { body: JSON.stringify({ decision, comment: reviewNote }) }); setReviewNote(''); }
  async function revoke() { const reason = window.prompt('Enter the formal reason for revoking this approved report:'); if (reason) await action('revoke', { body: JSON.stringify({ reason }) }); }
  if (!data) return <Loading label={error || 'Opening the controlled type-evaluation record...'} />;
  const { test, integrityValid, integrity } = data; const { instrument, evaluation } = test; const issued = ['Approved', 'Revoked'].includes(test.status); const editable = ['Draft', 'Returned'].includes(test.status); const canTest = ['TESTER', 'ADMIN'].includes(user.role); const canReview = ['REVIEWER', 'ADMIN'].includes(user.role);
  return <div className="report-detail">
    {location.state?.justCreated && <div className="success-banner"><FileCheck2 /><span><strong>Saved case created.</strong> Work can now be resumed section by section.</span></div>}
    {test.input?.demoFixture && <div className="warning-banner"><AlertTriangle /><span><strong>Synthetic SIH demonstration record.</strong> It demonstrates the governed digital workflow but is not physical-laboratory evidence or a statutory certificate.</span></div>}
    {test.coverageMode === 'LEGACY_PARTIAL' && <div className="warning-banner"><AlertTriangle /><span><strong>Legacy partial-coverage record.</strong> It predates the governed R 76 type-evaluation profile.</span></div>}
    <ErrorNotice>{error}</ErrorNotice>
    <div className="detail-actions"><button className="text-button back" onClick={() => navigate('/tests')}><ArrowLeft size={17} /> All cases</button><div>{editable && canTest && <button className="button primary" onClick={() => navigate(`/tests/${id}/edit`)}><Pencil size={17} /> Continue evaluation</button>}<button className="button secondary" onClick={() => window.print()}><Printer size={17} /> Print view</button>{issued && test.coverageMode !== 'LEGACY_PARTIAL' && integrityValid && <><button className="button secondary" onClick={() => downloadFile(`/api/tests/${test.id}/report.doc`, `${test.certificateNumber}-UNCONTROLLED.doc`)}><FileText size={17} /> Editable copy</button><button className="button primary" onClick={() => downloadFile(`/api/tests/${test.id}/report.pdf`, `${test.certificateNumber}.pdf`)}><Download size={17} /> Controlled PDF</button></>}</div></div>
    <section className="workflow-strip panel">{['Draft', 'Submitted', 'Approved'].map((status, index) => { const activeIndex = test.status === 'Returned' ? 0 : test.status === 'Revoked' ? 2 : ['Draft', 'Submitted', 'Approved'].indexOf(test.status); return <div key={status} className={index <= activeIndex ? 'done' : ''}><span>{index < activeIndex ? '✓' : index + 1}</span><strong>{status}</strong></div>; })}<StatusBadge status={test.status} /></section>
    <section className="certificate-head panel"><div className="certificate-id"><span className="eyebrow">{issued ? 'Issued type-evaluation report' : 'Resumable type-evaluation case'}</span><h2>{test.certificateNumber}</h2><p>{instrument.applicationNumber} · Revision {test.revision} · Record v{test.recordVersion} · Rules v{evaluation.ruleVersion}</p></div><div className={`certificate-result ${evaluation.passed ? 'passed' : 'failed'}`}><TestResultIcon passed={evaluation.passed} size="large" /><div><small>Technical result</small><strong>{evaluation.status}</strong><span>{evaluation.coverage?.percent ?? 0}% of rules-derived applicable work complete</span></div></div>{issued && <div className="certificate-qr"><img src={`/api/tests/${test.id}/qr.png`} alt="Verification QR code" /><span><QrCode size={15} /> Public verification</span></div>}</section>
    <section className="panel coverage-dashboard"><div><span className="eyebrow">Governed digital coverage manifest</span><h3>R 76-2 report + R 76-1 disposition matrix</h3><p>Not-applicable decisions come from the locked instrument questionnaire. Physical test validity and statutory interpretation remain with authorized experts.</p></div><div className="coverage-stat"><strong>{evaluation.coverage?.completedReportSections || 0}/{evaluation.coverage?.applicableReportSections || 0}</strong><span>report sections</span></div><div className="coverage-stat"><strong>{evaluation.requirements?.filter((row) => row.complete && row.applicability === 'Applicable').length || 0}/{evaluation.coverage?.applicableRequirementFamilies || 0}</strong><span>clause families</span></div><div className="coverage-stat"><strong>{evaluation.checklist?.filter((row) => row.complete && row.applicability === 'Applicable').length || 0}/{evaluation.coverage?.applicableDetailedChecklistRows || 0}</strong><span>detailed rows</span></div></section>
    {(editable || test.status === 'Submitted' || test.status === 'Approved') && <section className="panel control-panel"><div><span className="eyebrow">Four-eyes control</span><h3>{editable ? 'Complete and submit the case' : test.status === 'Submitted' ? 'Independent officer review required' : 'Issued record is locked'}</h3><p>{editable ? `${test.evidence.length} hashed evidence file(s) attached. The server recalculates every section again at submission.` : test.status === 'Submitted' ? 'No creator or contributor can review this record. Evidence bytes are re-hashed before approval.' : 'The report uses one final issued snapshot; correction requires revocation and one successor revision.'}</p></div><div className="control-actions">{editable && canTest && <button className="button primary" disabled={busy || !evaluation.complete} onClick={() => action('submit', { body: JSON.stringify({ expectedVersion: test.recordVersion }) })}><Send size={17} /> Submit saved version</button>}{test.status === 'Submitted' && canReview && <div className="review-box"><textarea value={reviewNote} onChange={(event) => setReviewNote(event.target.value)} placeholder="Mandatory reviewer note" /><div><button className="button secondary" disabled={busy} onClick={() => review('RETURN')}><XCircle size={16} /> Return</button><button className="button primary" disabled={busy} onClick={() => review('APPROVE')}><CheckCircle2 size={16} /> Approve and lock</button></div></div>}{test.status === 'Approved' && canReview && <button className="button danger-button" disabled={busy} onClick={revoke}>Revoke with reason</button>}{test.status === 'Revoked' && canTest && <button className="button secondary" disabled={busy} onClick={() => action('revise')}><RotateCcw size={17} /> Create correction revision</button>}</div></section>}
    <div className="report-columns"><div className="report-main">
      <section className="panel detail-section"><div className="panel-heading"><div><span className="eyebrow">Submitted type dossier</span><h3>Instrument snapshot</h3></div><StatusBadge status={instrument.status || 'Locked'} /></div><dl className="detail-list"><div><dt>Application</dt><dd>{instrument.applicationNumber}</dd></div><div><dt>Applicant</dt><dd>{instrument.applicant}</dd></div><div><dt>Manufacturer</dt><dd>{instrument.manufacturer}</dd></div><div><dt>Type designation</dt><dd>{instrument.typeDesignation}</dd></div><div><dt>Identification</dt><dd>{instrument.serialNumber}</dd></div><div><dt>Accuracy class</dt><dd>Class {instrument.accuracyClass}</dd></div><div><dt>Capacity</dt><dd>{instrument.minCapacity} to {instrument.maxCapacity} {instrument.unit}</dd></div><div><dt>Indication</dt><dd>{instrument.features?.indicatingMode} · {instrument.features?.electronic ? 'electronic' : 'non-electronic'}</dd></div></dl></section>
      <section className="panel detail-section"><div className="panel-heading"><div><span className="eyebrow">R 76-2 official order</span><h3>Every test and examination section</h3></div></div><div className="support-checks">{Object.values(evaluation.sections || {}).map((section) => <article key={section.id}><TestResultIcon passed={section.passed} /><div><strong>{section.number} · {section.name}</strong><p>{section.summary}</p><small>{section.applicability} · {section.procedure}</small></div><StatusBadge status={section.outcome} /></article>)}</div></section>
      <section className="panel detail-section"><div className="panel-heading"><div><span className="eyebrow">R 76-1 beyond the report checklist</span><h3>Normative clause-family disposition</h3></div></div><div className="table-scroll"><table><thead><tr><th>Clause</th><th>Requirement</th><th>Applicability</th><th>Outcome</th></tr></thead><tbody>{(evaluation.requirements || []).map((row) => <tr key={row.clause}><td><strong>{row.clause}</strong></td><td>{row.title}<small>{row.note}</small></td><td>{row.applicability}<small>{row.applicabilityReason}</small></td><td><StatusBadge status={row.outcome} /></td></tr>)}</tbody></table></div></section>
      <section className="panel detail-section"><div className="panel-heading"><div><span className="eyebrow">Evidence integrity</span><h3>Photographs, documents and bench sheets</h3></div>{editable && canTest && <div className="evidence-upload-controls"><select value={evidenceSection} onChange={(event) => setEvidenceSection(event.target.value)}>{Object.values(evaluation.sections || {}).map((section) => <option key={section.id} value={section.id}>{section.number} {section.name}</option>)}</select><input value={evidenceNote} onChange={(event) => setEvidenceNote(event.target.value)} placeholder="What this file proves" /><button className="button secondary small" onClick={() => fileRef.current?.click()} disabled={busy}><Camera size={16} /> {busy ? 'Hashing...' : 'Upload evidence'}</button><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp,application/pdf" capture="environment" onChange={uploadEvidence} /></div>}</div>{test.evidence.length ? <div className="evidence-list">{test.evidence.map((item) => <article key={item.id}><span><Upload /></span><div><strong>{item.name}</strong><small>Section {item.sectionId} · {item.note}</small><code>{item.fileSha256}</code></div>{item.storageKey && <button className="button secondary small" onClick={() => downloadFile(`/api/evidence/${item.id}`, item.name)}>Open</button>}</article>)}</div> : <div className="evidence-empty"><Camera /><strong>No evidence attached yet</strong><small>At least one section-16 dossier/construction file is required before submission.</small></div>}</section>
    </div><aside className="report-aside">
      <section className="panel aside-card"><span className="eyebrow">Observed by</span><div className="inspector-profile"><span>{test.inspectorName.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span><div><strong>{test.inspectorName}</strong><small>{test.inspectorId}</small></div></div><dl><div><dt>Laboratory</dt><dd>{test.laboratory}</dd></div><div><dt>Created</dt><dd>{new Date(test.createdAt).toLocaleString('en-IN')}</dd></div><div><dt>Environment</dt><dd>{test.environment?.temperature} C, {test.environment?.humidity}% RH, {test.environment?.barometricPressure || '—'} hPa</dd></div>{test.approvedBy && <div><dt>Reviewer</dt><dd>{test.approvedBy.name} ({test.approvedBy.officerId})</dd></div>}</dl></section>
      {issued && <section className="panel aside-card verify-card"><span className="verify-shield"><ShieldCheck /></span><h3>{integrityValid ? 'Stored content and status are consistent' : 'Integrity warning'}</h3><p>{integrity?.version >= 2 ? 'The issued snapshot binds the dossier, executable-rules hash, observations, equipment and evidence-byte hashes. A second hash binds current revocation status. These are database consistency checks; a government deployment should add externally managed digital signatures.' : integrity?.limitation}</p><code className="hash-code">{test.integrityHash}</code>{test.statusIntegrityHash && <code className="hash-code">{test.statusIntegrityHash}</code>}<a className="button primary full" href={`/verify/${test.verificationCode}`} target="_blank" rel="noreferrer">Open public verification <ExternalLink size={16} /></a></section>}
      {test.reviewHistory?.length > 0 && <section className="panel aside-card"><span className="eyebrow">Review history</span>{test.reviewHistory.map((review) => <div className="review-history" key={review.at}><strong>{review.decision}</strong><small>{review.reviewer.name} · {new Date(review.at).toLocaleString('en-IN')}</small><p>{review.comment}</p></div>)}</section>}
    </aside></div>
  </div>;
}
