const item = (id, clause, text, applies = 'selfSemi', group = '17.1 General') => ({ id, clause, text, applies, group });

// Clause-level rows needed to reproduce sections 17.1-17.4 of R 76-2.
// Repeated clause numbers have stable suffixes because the official form tests distinct requirements.
export const R76_2_CHECKLIST = Object.freeze([
  item('7.1.1-primary-markings', '7.1.1', 'Manufacturer identity, accuracy class, Max, Min and e are marked; each applicable range is identified.', 'always'),
  item('7.1.2-additional-markings', '7.1.2', 'Serial/type approval, d where d is below e, software ID, tare, safe load, temperature and applicable ratios/ranges are marked.', 'always'),
  item('7.1.3-special-use', '7.1.3', 'All required special-use, exclusive-use, stamping-limit and not-for-direct-sales wording is present.', 'always'),
  item('3.2-mixed-classes', '3.2', 'Mixed accuracy-class ranges, where present, are marked and classified correctly.', 'always'),
  item('4.15-visible-wording', '4.15', 'Not-for-direct-sales wording is visible where the instrument resembles a direct-sales instrument.', 'directSalesSimilar'),
  item('7.1.4-marking-quality', '7.1.4', 'Markings are indelible, readable, grouped, visible and positioned correctly near the display or on an accessible plate/software view.', 'always'),
  item('7.1.5.1-receptors', '7.1.5.1', 'Each receptor or measuring device bears its identification and Max, Min, e and applicable Lim/T.', 'multipleComponents'),
  item('7.1.5.2-main-parts', '7.1.5.2', 'Separately built main parts repeat the required identification.', 'moduleCompatibility'),
  item('4.1.1.3-module-identification', '4.1.1.3', 'Separately type-examined devices are unambiguously identified.', 'moduleCompatibility'),
  item('7.2-verification-mark', '7.2', 'Verification mark is non-removable, easy to apply and visible without moving the instrument.', 'always'),
  item('7.2.2-mark-conservation', '7.2.2', 'Verification-mark support preserves the mark and meets the minimum stamping/self-adhesive area.', 'always'),
  item('4.1.2.4-securing-location', '4.1.2.4', 'Components and preset controls requiring security have an appropriate physical location and form.', 'always'),
  item('4.1.2.4a-intervention', '4.1.2.4(a)', 'Legal status is recognizable and intervention leaves durable evidence.', 'always'),
  item('4.1.2.4b-parameter-protection', '4.1.2.4(b)', 'Legally relevant parameters and reference numbers are protected from unauthorized change.', 'always'),
  item('4.1.2.4c-reference-number', '4.1.2.4(c)', 'A facility exists to affix or display the securing reference number.', 'always'),
  item('4.1.2.5-span-adjustment', '4.1.2.5', 'Span adjustment is protected from external influence after securing.', 'always'),
  item('4.1.2.6-gravity-compensation', '4.1.2.6', 'Gravity compensation, when present, is inaccessible after securing.', 'always'),
  item('8.2.1-type-documentation', '8.2.1; 8.2.1.1', 'Instrument, module, family and component characteristics are documented for type approval.', 'always'),
  item('3.10.2-module-specification', '3.10.2', 'Submitted modules and their functions are fully specified.', 'moduleCompatibility'),
  item('3.10.2.1-error-fractions', '3.10.2.1', 'Each separately examined module has an approved error fraction pi.', 'moduleCompatibility'),
  item('3.10.4-family', '3.10.4', 'The instrument family and permitted variants are defined.', 'always'),
  item('8.2.1.2-descriptive-docs', '8.2.1.2', 'Applicable drawings, descriptions, manuals, software and technical documents are supplied.', 'always'),
  item('5.3.6.1-declaration', '5.3.6.1', 'The manufacturer declaration for interface protection is recorded.', 'electronic'),
  item('3.9.1.1-tilt-limit', '3.9.1.1', 'The manufacturer-defined limiting tilt is declared where applicable.', 'tilting'),
  item('8.2.2-document-examination', '8.2.2', 'Documents and functions were examined, spot-checked and any accepted external reports identified.', 'always'),
  item('4.2.1-reading', '4.2.1', 'Reading is reliable, easy and unambiguous; analog inaccuracy, form and juxtaposition comply.', 'selfSemi'),
  item('4.2.2.1-units-interval', '4.2.2.1', 'Mass/price units and scale intervals follow the prescribed form and remain consistent across display, print and tare.', 'selfSemi'),
  item('4.2.2.2-digital-form', '4.2.2.2', 'Digital decimal placement and significant/non-significant zero presentation comply.', 'digital'),
  item('4.2.3-range-limits', '4.2.3', 'Indication is inhibited above Max plus 9e and below the allowed negative range.', 'selfSemi'),
  item('4.2.4-approximate-device', '4.2.4', 'Any approximate indicating device has the required interval and cannot be mistaken for a primary indication.', 'auxiliaryIndication'),
  item('4.2.5-semi-extension', '4.2.5', 'Semi-self-indicating extension does not exceed the permitted self-indicating capacity.', 'selfSemi'),
  item('4.3.1-analog-marks', '4.3.1', 'Analog scale-mark thickness and length comply.', 'analog'),
  item('4.3.2-analog-spacing', '4.3.2', 'Analog scale spacing complies.', 'analog'),
  item('4.3.3-analog-movement', '4.3.3', 'Analog movement is limited correctly below zero and above self-indication capacity.', 'analog'),
  item('4.3.4-damping', '4.3.4', 'Damping achieves the required stable reading without preventing response.', 'analog'),
  item('4.4.1-dynamic-display', '4.4.1', 'The previous digital indication disappears within one second after a load change.', 'digital'),
  item('4.4.2-stability-actions', '4.4.2', 'Stored/printed values, zero and tare meet stability and accuracy requirements; unstable operations are inhibited.', 'digital'),
  item('4.4.3-extended-indication', '4.4.3', 'Extended indication is time/key limited, non-differentiated and cannot be printed.', 'digital'),
  item('4.4.4-other-indications', '4.4.4', 'Other digital indications are identified, unambiguous and cannot be confused with weighing results.', 'digital'),
  item('4.4.5-printer', '4.4.5', 'Printing is permanent, clear, correctly sized and identified, and unstable printing is inhibited.', 'printer'),
  item('4.4.6-memory', '4.4.6', 'Storage, transfer and totalization are inhibited while equilibrium is unstable.', 'dataStorage'),
  item('3.4.1-auxiliary-type', '3.4.1', 'Auxiliary indication type, class restrictions, decimal position and multi-interval prohibition comply.', 'auxiliaryIndication'),
  item('3.4.2-auxiliary-interval', '3.4.2', 'Auxiliary actual and verification intervals satisfy d < e <= 10d.', 'auxiliaryIndication'),
  item('3.6.3-multiple-indications', '3.6.3', 'Multiple indications differ by no more than mpe; digital display and print agree exactly.', 'multipleIndications'),
  item('3.6.4-balancing-method', '3.6.4', 'Results after changing the balancing method differ by no more than mpe.', 'selfSemi'),
  item('3.9.1.1-tilt-controls', '3.9.1.1', 'Tilt limit, level indication/sensor, alarm or inhibition and print/transmission behavior comply.', 'tilting'),
  item('4.5.1-zero-range', '4.5.1', 'Zero-setting does not alter Max and the combined initial/automatic/tracking ranges comply.', 'zero'),
  item('4.5.2-zero-accuracy', '4.5.2', 'Zero-setting and zero-tracking accuracy is within 0.25e.', 'zero'),
  item('4.5.3-zero-multiple-range', '4.5.3', 'Zero-setting remains effective in higher ranges when loaded switching is possible.', 'multipleRange'),
  item('4.5.4-zero-controls', '4.5.4', 'Zero/tare controls are separate where required and semi-automatic zero operates only under permitted conditions.', 'zero'),
  item('4.5.5-zero-indication', '4.5.5', 'Zero indication is within 0.25e and the printing exception is handled correctly.', 'zero'),
  item('4.5.6-automatic-zero', '4.5.6', 'Automatic zero operates only at stable equilibrium and after the prescribed below-zero period.', 'zero'),
  item('4.5.7-zero-tracking', '4.5.7', 'Zero-tracking operating conditions, correction rate and post-tare total effect comply.', 'zero'),
  item('4.6.1-tare-general', '4.6.1', 'Applicable clauses 4.1 through 4.4 are fulfilled by the tare device.', 'tare'),
  item('4.6.2-tare-interval', '4.6.2', 'Tare scale interval dT equals d.', 'tare'),
  item('4.6.3-tare-accuracy', '4.6.3', 'Tare-device accuracy meets the indication-specific limit.', 'tare'),
  item('4.6.4-tare-range', '4.6.4', 'Tare operation is prevented at/below zero effect and above maximum tare.', 'tare'),
  item('4.6.5-tare-visibility', '4.6.5', 'Tare operation and net/gross state are visibly and correctly identified.', 'tare'),
  item('4.6.6-subtractive-tare', '4.6.6', 'Subtractive tare prevents use above Max or clearly indicates capacity reached.', 'tare'),
  item('4.6.7-tare-multiple-range', '4.6.7', 'Tare remains effective and is rounded correctly across weighing ranges.', 'multipleRangeTare'),
  item('4.6.8-stable-tare', '4.6.8', 'Semi-automatic or automatic tare operates only at stable equilibrium.', 'tare'),
  item('4.6.9-combined-zero-tare', '4.6.9', 'Combined zero/tare satisfies accuracy, zero indication and zero-tracking requirements.', 'tare'),
  item('4.6.10-consecutive-tare', '4.6.10', 'Consecutive simultaneous tare values are clearly designated.', 'tare'),
  item('4.6.11-net-gross-print', '4.6.11', 'Printed gross, net and tare values use the required designations and identification.', 'tare'),
  item('4.7.1-preset-rounding', '4.7.1', 'Preset tare interval, rounding and multiple-range/multi-interval behavior comply.', 'presetTare'),
  item('4.7.2-preset-operation', '4.7.2', 'Preset tare consecutive-operation, cancellation and automatic identification rules comply.', 'presetTare'),
  item('4.7.3-preset-visibility', '4.7.3', 'Preset tare can be displayed and prints with calculated net using PT identification.', 'presetTare'),
  item('4.8.1-locking-positions', '4.8.1', 'Only two stable locking positions exist and weighing occurs only in the weighing position.', 'locking'),
  item('4.8.2-locking-shown', '4.8.2', 'Locking positions are clearly shown.', 'locking'),
  item('4.10-range-selection', '4.10', 'Range identification and permitted automatic/manual range-switching conditions comply.', 'multipleRange'),
  item('4.11-selection-devices', '4.11; 4.11.1-.4', 'Selection compensates no-load effects, provides unambiguous zero, inhibits weighing during selection and identifies combinations.', 'multipleComponents'),
  item('4.12.1-comparator-zones', '4.12.1', 'Plus/minus comparator zones are clearly distinguished.', 'comparator'),
  item('4.12.2-comparator-scale', '4.12.2', 'Comparator scale includes divisions on both sides of zero and shows d=e.', 'comparator'),
  item('4.17.1-counting-scale', '4.17.1', 'Mechanical counting scale includes the required divisions and displayed d=e.', 'mechanicalCounting'),
  item('4.17.2-counting-ratio', '4.17.2', 'Counting ratio is clearly shown for each platform/scale mark.', 'mechanicalCounting'),
  item('4.20-operation-modes', '4.20', 'Active mode is identifiable; manual/automatic return and switch-off zero checks comply.', 'multipleModes'),

  item('4.5.4-direct-zero-tare-key', '4.5.4', 'A combined semi-automatic zero/tare key is not used.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.8.1-direct-preweigh', '4.8.1', 'A preweigh position is not provided.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.13.10-direct-counting', '4.13.10', 'Mechanical counting ratio is restricted to 1/10 or 1/100.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.13.5-direct-operation', '4.13.5', 'Weighing is impossible during locking or addition/removal of weights.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.13.7-direct-auxiliary', '4.13.7', 'Auxiliary and extended indicating devices are not available.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.13.9-direct-fault', '4.13.9', 'Faults are visible/audible to the customer and transmission is prevented until action or removal.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.13.1-display-arrangement', '4.13.1; 4.13.6', 'Vendor/customer display arrangement, required indications, figure size and distinguishable weights comply.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.13.2-direct-zero', '4.13.2', 'Non-automatic zero can be operated only with a tool.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.13.3-direct-tare', '4.13.3', 'Direct-sales tare restrictions, customer visibility, single-tare and gross-recall rules comply.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.13.3.1-direct-manual-tare', '4.13.3.1', 'Non-automatic tare displacement is no more than e for 5 mm.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.13.3.2-direct-semi-tare', '4.13.3.2', 'Semi-automatic tare reduction/cancellation and unloaded behavior comply.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.13.3.3-direct-auto-tare', '4.13.3.3', 'Automatic tare is not provided.', 'directSales', '17.2 Direct sales and price functions'),
  item('4.13.4-direct-preset-tare', '4.13.4', 'Preset tare has a separate display and permitted cancellation/PLU behavior.', 'directSalesPresetTare', '17.2 Direct sales and price functions'),
  item('4.13.11-self-service', '4.13.11', 'Self-service display arrangement and printed product designation comply.', 'selfService', '17.2 Direct sales and price functions'),
  item('4.14-direct-general', '4.14', 'All direct-sales requirements are met by the price-computing instrument.', 'priceComputing', '17.2 Direct sales and price functions'),
  item('4.14.1-price-indications', '4.14.1', 'Unit price, price-to-pay and non-weighed-article indications are correctly identified.', 'priceComputing', '17.2 Direct sales and price functions'),
  item('4.14.2-price-calculation', '4.14.2', 'Price scales and multiplication satisfy the permitted rounding/calculation difference.', 'priceComputing', '17.2 Direct sales and price functions'),
  item('4.14.3-price-operation', '4.14.3', 'Price indication duration, freezing, printing and memory safeguards comply.', 'priceComputing', '17.2 Direct sales and price functions'),
  item('4.14.4-trade-functions', '4.14.4', 'Trade/management functions print transactions and cannot be confused with weighing.', 'priceComputing', '17.2 Direct sales and price functions'),
  item('4.14.4.1-nonweighed', '4.14.4.1', 'Non-weighed and multiple-equal-article functions comply.', 'priceComputing', '17.2 Direct sales and price functions'),
  item('4.14.4.2-totalization', '4.14.4.2', 'Transaction totalization, algebraic total and linked price intervals comply.', 'priceComputing', '17.2 Direct sales and price functions'),
  item('4.14.4.3-vendor-customer', '4.14.4.3', 'Vendor/customer association is unambiguous.', 'priceComputing', '17.2 Direct sales and price functions'),
  item('4.14.4.4-cancellation', '4.14.4.4', 'Printed and unprinted transaction cancellation is controlled.', 'priceComputing', '17.2 Direct sales and price functions'),
  item('4.14.4.5-extra-print', '4.14.4.5', 'Extra printed information is correlated and non-interfering.', 'priceComputing', '17.2 Direct sales and price functions'),
  item('4.16-price-labeling', '4.16', 'Price-labeling prerequisites, display verification, Min inhibition and fixed-label mode comply.', 'priceLabeling', '17.2 Direct sales and price functions'),
  item('4.18.1-mobile-outdoor', '4.18.1', 'Mobile outdoor tilt, movement, zero/tare and weighing-window protections comply.', 'mobileOutdoor', '17.2 Direct sales and price functions'),
  item('4.18.2-mobile-other', '4.18.2', 'Other mobile instruments provide easy leveling, a visible indicator and leveling instructions.', 'mobileOther', '17.2 Direct sales and price functions'),

  item('5.1.1-significant-fault', '5.1.1', 'Significant-fault indication cannot be confused with any other message.', 'electronic', '17.3 Electronic instruments'),
  item('5.2-fault-action', '5.2', 'The instrument becomes inoperative or alarms until action or fault removal.', 'electronic', '17.3 Electronic instruments'),
  item('5.3.1-display-test', '5.3.1', 'Switch-on test activates and deactivates every display sign long enough to inspect.', 'electronic', '17.3 Electronic instruments'),
  item('5.3.6-interface-general', '5.3.6', 'Interfaces cannot allow inadmissible influence on metrological functions.', 'electronic', '17.3 Electronic instruments'),
  item('5.3.6.1-interface-protection', '5.3.6.1', 'Interfaces prevent misleading data, falsification and unauthorized adjustment.', 'electronic', '17.3 Electronic instruments'),
  item('5.3.6.2-interface-security', '5.3.6.2', 'Any non-compliant interface can be secured.', 'electronic', '17.3 Electronic instruments'),
  item('5.3.6.3-transmitted-data', '5.3.6.3', 'Transmitted data permits connected peripherals to comply.', 'electronic', '17.3 Electronic instruments'),
  item('5.3.6-interface-functions', '5.3.6', 'Interface-initiated metrological functions comply with R 76-1.', 'electronic', '17.3 Electronic instruments'),

  item('5.5.1-embedded-declaration', '5.5.1; G.1', 'Embedded-software environment, legal functions, securing and software identification are documented and verified.', 'embeddedSoftware', '17.4 Software-controlled devices'),
  item('5.5.2.2d-software-docs', '5.5.2.2(d); G.2.1', 'Complete legally relevant programmable/loadable software documentation is supplied.', 'programmableSoftware', '17.4 Software-controlled devices'),
  item('5.5.2.2a-software-protection', '5.5.2.2(a)', 'Software is protected from accidental/intentional change and intervention leaves evidence.', 'programmableSoftware', '17.4 Software-controlled devices'),
  item('G.2.2.1-closed-os', 'G.2.2.1', 'For an inaccessible OS/program environment, allowed commands and the environment declaration are complete.', 'closedSoftware', '17.4 Software-controlled devices'),
  item('G.2.2.2-open-os', 'G.2.2.2', 'For an accessible OS/program environment, code signature/checksum is verified and falsification prevents start.', 'openSoftware', '17.4 Software-controlled devices'),
  item('G.2.2.3-device-parameters', 'G.2.2.3', 'Device-specific parameters are protected and changes are covered by an effective audit trail.', 'programmableSoftware', '17.4 Software-controlled devices'),
  item('5.5.2.2b-software-separation', '5.5.2.2(b); G.2.3', 'Legally relevant software is separated through a protected interface with complete function/data definitions.', 'programmableSoftware', '17.4 Software-controlled devices'),
  item('5.5.2.2c-software-id', '5.5.2.2(c); G.2.4', 'Software ID covers modules/runtime parameters, is easily displayed and matches the approved signature/checksum.', 'programmableSoftware', '17.4 Software-controlled devices'),
  item('5.5.3-storage-class', '5.5.3; G.3.1', 'The data-storage device is correctly classified and its legally relevant software is examined.', 'dataStorageSoftware', '17.4 Software-controlled devices'),
  item('5.5.3.1-storage-capacity', '5.5.3.1; G.3.2', 'Storage capacity, correct retrieval and loss prevention are adequate.', 'dataStorageSoftware', '17.4 Software-controlled devices'),
  item('5.5.3.2-stored-fields', '5.5.3.2; G.3.3', 'Stored data includes mass results, tare, units, identifiers and integrity signature/checksum.', 'dataStorageSoftware', '17.4 Software-controlled devices'),
  item('5.5.3.3-data-protection', '5.5.3.3; G.3.4', 'Stored/transmitted data is protected, integrity-checked and identifiable.', 'dataStorageSoftware', '17.4 Software-controlled devices'),
  item('5.5.3.4-transaction-id', '5.5.3.4; G.3.5', 'The storage identification number is printed on the official transaction medium.', 'dataStorageSoftware', '17.4 Software-controlled devices'),
  item('5.5.3.5-auto-storage', '5.5.3.5; G.3.6', 'Legally relevant data is stored automatically.', 'dataStorageSoftware', '17.4 Software-controlled devices'),
  item('5.5.3.6-verification-output', '5.5.3.6; G.3.7', 'Stored data can be printed or displayed for legal verification.', 'dataStorageSoftware', '17.4 Software-controlled devices'),
]);

// Requirements the official R 76-2 checklist explicitly says it does not exhaust.
export const R76_1_SUPPLEMENT = Object.freeze([
  item('2.1-units-complete', '2.1', 'Every legally relevant mass unit and permitted non-mass indication follows the prescribed SI form.', 'always', 'R 76-1 supplement'),
  item('2.4-application-complete', '2.4', 'Every device that performs a covered function is assessed against the requirement applying to that function.', 'always', 'R 76-1 supplement'),
  item('2.5-terminology-complete', '2.5', 'Binding terms and symbols used in the dossier have the R 76 meaning and are applied consistently.', 'always', 'R 76-1 supplement'),
  item('3.7.1-standard-weights', '3.7.1', 'Standard weights and their correction or error demonstrate the required relationship to the instrument mpe.', 'always', 'R 76-1 supplement'),
  item('3.7.2-auxiliary-standard', '3.7.2', 'Any auxiliary verification device used as a standard has adequate accuracy and is included in the uncertainty decision.', 'auxiliaryVerification', 'R 76-1 supplement'),
  item('3.7.3-substitution-standard', '3.7.3', 'Any substitution of standard weights follows the prescribed method and substitution-error controls.', 'substitutionStandards', 'R 76-1 supplement'),
  item('3.10.3-peripheral-devices', '3.10.3', 'Connected or submitted peripheral devices are identified and shown not to influence the weighing result inadmissibly.', 'peripherals', 'R 76-1 supplement'),
  item('4.1.2.1-fraudulent-use', '4.1.2.1', 'Construction prevents fraudulent use and makes legally relevant intervention evident.', 'selfSemi', 'R 76-1 supplement'),
  item('4.1.2.2-breakdown-maladjustment', '4.1.2.2', 'Accidental breakdown or maladjustment cannot occur without an evident effect or protective response.', 'selfSemi', 'R 76-1 supplement'),
  item('4.1.2.3-controls-adjustment', '4.1.2.3', 'Controls and adjustment devices cannot assume positions that facilitate fraudulent use.', 'selfSemi', 'R 76-1 supplement'),
  item('5.1.2-durable-compliance', '5.1.2', 'The electronic instrument is designed and manufactured to maintain metrological compliance durably.', 'electronic', 'R 76-1 supplement'),
  item('5.1.4-fault-strategy', '5.1.4', 'The manufacturer declares the significant-fault detection strategy and any applicable permitted exception.', 'electronic', 'R 76-1 supplement'),
  item('5.5.3.7-storage-certificate-id', '5.5.3.7; G.3', 'Any separately tested data-storage device is identified by its evaluation certificate and approved configuration.', 'dataStorageSoftware', 'R 76-1 supplement'),
  item('A.4.13-portable-road-weigher', 'A.4.13; 3.11; 4.19', 'The complete additional test plan for a portable instrument weighing road vehicles is recorded and performed.', 'portableRoadVehicle', 'R 76-1 supplement'),
  item('6.2-nonself-indicators', '6.2.1-6.2.3', 'Every applicable non-self-indicating device, poise and indication construction rule is examined.', 'nonSelf', 'R 76-1 supplement'),
  item('6.3-nonself-construction', '6.3.1-6.3.5', 'Knife edges, bearings, ratio, equilibrium and load-receptor construction follow the applicable non-self-indicating rules.', 'nonSelf', 'R 76-1 supplement'),
  item('4.1.1.1-suitability-application', '4.1.1.1', 'Design is suitable for its intended application.', 'selfSemi', 'R 76-1 supplement'),
  item('4.1.1.2-suitability-use', '4.1.1.2', 'Construction is suitably robust for its intended period and environment of use.', 'selfSemi', 'R 76-1 supplement'),
  item('4.1.1.3-suitability-verification', '4.1.1.3', 'Construction permits the required metrological controls and identification.', 'selfSemi', 'R 76-1 supplement'),
  item('3.2-classification-complete', '3.2', 'All accuracy-class criteria, minimum/maximum interval counts, Min and e/d relationships comply.', 'always', 'R 76-1 supplement'),
  item('3.3-multi-interval-complete', '3.3', 'All multi-interval range, interval and tare requirements comply.', 'multiInterval', 'R 76-1 supplement'),
  item('4.9-aux-verification-complete', '4.9', 'Every removable or fixed auxiliary verification device complies.', 'auxiliaryVerification', 'R 76-1 supplement'),
  item('6-non-self-complete', '6.1-6.9', 'The complete applicable non-self-indicating construction path has been examined.', 'nonSelf', 'R 76-1 supplement'),
]);

export const ALL_CHECKLIST_REQUIREMENTS = Object.freeze([...R76_2_CHECKLIST, ...R76_1_SUPPLEMENT]);
